# Generated by Django 4.2.20 on 2025-04-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0003_remove_customuser_last_login_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
